language: python

os: linux
sudo: required
dist: trusty

before_script:
  - lsb_release -a
  - ping -c1 localhost

python:
  - 2.7

addons:
  apt:
    packages:
      - rsync
      - openssh-client
      - openssh-server

before_install:
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/tar_1.28-2.1_amd64.deb
  - sudo dpkg -i tar_1.28-2.1_amd64.deb

install:
  - rsync --version
  - ssh -V
  - ls -la ${HOME}/.ssh
  - service ssh status
  - ssh-keygen -t rsa -N "" -f ${HOME}/.ssh/id_rsa
  - cat ${HOME}/.ssh/id_rsa.pub >> ${HOME}/.ssh/authorized_keys

script:
  - tar --version
  - lsb_release -a
  - test/test_simple.sh
