language: python

os: linux
sudo: required
dist: trusty

before_script:
  - lsb_release -a
  - ping -c1 localhost

python:
  - 2.7

addons:
  apt:
    packages:
      - rsync
      - openssh-client
      - openssh-server

before_install:
  - sudo add-apt-repository -r "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get update -q
  - sudo apt-get install tar/trusty-backports

install:
  - rsync --version
  - ssh -V
  - ls -la ${HOME}/.ssh
  - service ssh status
  - ssh-keygen -t rsa -N "" -f ${HOME}/.ssh/id_rsa
  - cat ${HOME}/.ssh/id_rsa.pub >> ${HOME}/.ssh/authorized_keys

script:
  - tar --version
  - lsb_release -a
  - test/test_simple.sh
