language: python

os: linux
sudo: required
dist: trusty

python:
  - 2.7

addons:
  apt:
    packages:
      - rsync
      - openssh-client
      - openssh-server

before_install:
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/tar_1.28-2.1_amd64.deb
  - sudo dpkg -i tar_1.28-2.1_amd64.deb
  - ssh-keygen -t rsa -N "" -f ${HOME}/.ssh/id_rsa
  - cat ${HOME}/.ssh/id_rsa.pub >> ${HOME}/.ssh/authorized_keys

install:
  - pip2 install click watchdog paramiko

script:
  - test/test_simple.sh

notifications:
  email:
    recipients:
      - emdej@emdej.com
    on_success: always # default: change
    on_failure: always # default: always
